# Generated by Django 2.2.5 on 2020-01-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30, verbose_name='項目')),
                ('category', models.IntegerField(choices=[(0, '未分類'), (1, '飲食'), (2, '衣服'), (3, '交通'), (4, '教育'), (5, '娛樂'), (99, '其它')], default=0, verbose_name='支出類別')),
                ('amount', models.IntegerField(default=0, verbose_name='支出金額')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
